### ISSUE TITLE
The dirty status of connection makes it very inconvenient to use the client in REPL and notebooks 

### ISSUE THREAD

**Issue by waralex** [JuliaDatabases/ClickHouse.jl#19]
The problem is that for any error, including a syntax error in sql query, the connection remains in the dirty status and you need to make a new connection. At the same time, it is very easy to make such an error when conducting an exploration in a large database (for example, it is not correct to write the name of a table field). The need to reconnect itself is annoying, but even worse is that a session is linked to the connection, i.e. 'USE ...', temporary tables, etc. Overfilling them again is quite painful :(

I would like to discuss how best to solve this problem. It seems to me that after implementing all types this is the blocking issue for the release of the next version of the package

**Comment by athre0z** [comment]
Yeah, agree that this is annoying. 

It is a workaround for a harder problem -- correctly recovering from failure in all imaginable exception locations. For example, when we do an insert, the user passes an iterator of 5 blocks where the first 3 ones are good but the 4. one has some non-CH type in it, we have to throw an exception and would have to correctly shut down the insert by sending the final empty block or the server will not allow any other packet. 

In the early days of this client, a loooot of things used to go wrong on a regular basis and you would end up with broken connections because the server was waiting for different packets etc. and it confused me a lot because it often does weird things in this case, that's why I implemented the dirty mechanic. However, at the current stage, I think it would be pretty doable to exhaustively implement recovery for all possible error paths. I'll look into that today.

**Comment by waralex** [comment]
We Got rid of the `dirty` status, I'm closing the issue
