### ISSUE TITLE
Inserting into nullable columns

### ISSUE THREAD

**Issue by SpinolaHours** [JuliaDatabases/ClickHouse.jl#23]
Hi there,

I've just started using this library.

It seems like I can only insert columns that contain a missing value into nullable columns.

Is this expected behavior?

`execute(conn, """
    CREATE TABLE TestTable
        (a Int64, b String NULL)
    ENGINE = MergeTree
    ORDER BY a
""")`

`tbl = [Dict(:a=> [0,1,2], :b=> ["aa", "bb", "cc"])]`

`insert(conn, "TestTable", tbl)`

produces this error:
`ERROR: MethodError: no method matching fill(::Int8, ::Tuple{UnitRange{Int64}})
Closest candidates are:
  fill(::Any, ::Union{Integer, AbstractUnitRange}...) at array.jl:471
  fill(::Any, ::Tuple{}) at array.jl:474
  fill(::Any, ::Tuple{Vararg{Integer,N}}) where N at array.jl:473`

This is the first issue I've ever raised so please let me know if there is other information I should be providing.
Thanks

**Comment by waralex** [comment]
Hi, @SpinolaHours!
I added a PR  https://github.com/JuliaDatabases/ClickHouse.jl/pull/24 with a fix for this bug.
For your information, I have been working on another refactoring of this package for quite some time, including bringing the interfaces for inserting data into a suitable form. Due to the lack of time, the work is not going very fast, but hopefully in a month or two I will release a big release.

Thank you for your interest in the package!

**Comment by SpinolaHours** [comment]
@waralex , thanks so much. Looking forward to the next release!

I'd be happy to help if I can (although I'm not a particularly experienced programmer).
