### ISSUE TITLE
Potential collaboration

### ISSUE THREAD

**Issue by quinnj** [JuliaDatabases/ClickHouse.jl#4]
Hey there, I was really excited to see someone had started a native Julia Clickhouse package. Wondered if you'd be open to collaborating on a few things:

* [Tables.jl](https://github.com/JuliaData/Tables.jl) support for loading data into a clickhouse table (would be very close to the already implemented load functionality)
* [DBInterface.jl](https://github.com/JuliaDatabases/DBInterface.jl) support; again, this is already mostly implemented (connect, close, execute), but it can be nice to have an expected interface
* Move to JuliaDatabases organization? I've worked on various database wrapper/client packages for Julia and I think it's helpful to pool resources and get related things together.
* What are the biggest pieces of missing functionality? Happy to jump in and help however I can; if you have a list in your mind of things you'd like to tackle, I'm happy to help take a stab

**Comment by athre0z** [comment]
Hi Jacob! 

Sure, sounds great! The time that I can allocate to this project is somewhat limited, so I'm actually pretty happy to move this to a place where there are competent people that have push access in case this repo gains some more traction at some point and I don't have the time to handle it. Let me know how we get this started -- do I just move the repo to the JuliaDatabases orga?

Implementing some standard interfaces is cool with me, however we should make sure to additionally retain the blockwise columnar interface that allow for maximum throughput due to it being very close to what is actually transferred over the wire, allowing for many column types to just be written to IO as is, without performing additional copies, saving a lot of gather/scatter operations for row/column transformation. Personally, my primary reason to use CH is its brutal IO capacity for large queries and killing that would make this lib unattractive to me.

> What are the biggest pieces of missing functionality? Happy to jump in and help however I can; if you have a list in your mind of things you'd like to tackle, I'm happy to help take a stab

To be honest, there's quote a lot of things to make this thing a production grade client:
- Support for most non-trivial types
  - `Nullable`
  - `LowCardinality`
  - `Nested`
  - `Array`
  - .. anything that isn't explicitly listed as supported in the doc ..
- Proper parsing for composed types, e.g. `Nullable(Enum8(...))`
  - I took a look around and didn't find any nice actively maintained parser lib
  - Also, I was too lazy to roll my own one, particularly since I don't really know shit about writing solid parsers
  - The current parsing for `Enum` is based on regexps, and it's ugly
- Support for escaping queries to allow safely inserting untrusted strings into queries
- Connection pooling

**Comment by quinnj** [comment]
Awesome. I invited you as a member of JuliaDatabases org, so that should allow you to transfer the repo over there.

I agree on the need for performance; the only reason I know about CH is because of its perf, so we definitely need to not become a bottleneck. The Tables.jl interface should be amenable to that and DBInterface is a higher-level interface that sits on top of everything, so no worries there. I can start taking a look at that.

Great list of additional items. I'm also not quite sure on the time I'll have, but I'm kind of itching for a new Julia project and this is attractive because it's already got a great foundation!

**Comment by athre0z** [comment]
Aaand it's moved!

If you need any reference for ClickHouse wire protocol related things, I recommend taking a look at these repos:

https://github.com/mymarilyn/clickhouse-driver (Python)
https://github.com/suharev7/clickhouse-rs (Rust)

When in doubt, the official ClickHouse C++ client can also be a good reference, however due to it's complexity it's oftentimes a bit harder to navigate. Also don't hesitate to ask me for help!

Do you have any plans on what you want to work on first?

**Comment by athre0z** [comment]
I lost my push perms for the repo in the progress btw, it would be great if you could assign me team or whatever is necessary to restore them.

**Comment by athre0z** [comment]
I transformed the most important TODO points into separate issues to improve discoverability for any potential contributors. With the migration being complete, I think we can now close this issue and continue with the more specific ones. :)

**Comment by quinnj** [comment]
Sounds great! Definitely happy to help review PRs; I've been caught up in implementing apache arrow for Julia the last few weeks (https://github.com/JuliaData/Arrow.jl), but it's coming along nicely and when it's all sorted out, I want to pick up Tables.jl-integration here so we can easily transfer data between 😄
